name: Test
on: [workflow_dispatch]
permissions: write-all

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  WS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Test-job:
    name: Deplot to staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: SetupTerrafrom
        uses: hashicorp/setup-terraform@v2
      - name: TerrafromInit
        run: terraform init
      - name: terraform Plan
        run:  terrafrom Plan
